apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: certificaterequests.certman.managed.openshift.io
spec:
  group: certman.managed.openshift.io
  names:
    kind: CertificateRequest
    listKind: CertificateRequestList
    plural: certificaterequests
    singular: certificaterequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            baseDnsDomain:
              description: Base DNS Domain
              type: string
            dnsNames:
              description: DNSNames is a list of subject alt names to be used on the Certificate.
              items:
                type: string
              type: array
            renewBeforeDays:
              description: Certificate renew before expiration duration in days.
              format: int64
              type: integer
            awsCredentials:
              description: Credentials refers to a secret that contains the AWS account access credentials.
              type: object
            certificateSecret:
              description: CertificateSecret contains the TLS certificates issued for the cluster.
              type: object
          required:
          - certificateSecret
          - awsSecrets
          - baseDnsDomain
          - dnsNames
        status:
          type: object
          properties:
            issued:
              description: Issued is true once certificates have been issued.
              type: boolean
            notAfter:
              description: The expiration time of the certificate stored in the secret named by this resource in spec.secretName.
              format: date-time
              type: string
            notBefore:
              description: The earliest time and date on which the certificate stored in the secret named by this resource in spec.secretName is valid.
              format: date-time
              type: string
            issuerName:
              description: The entity that verified the information and signed the certificate.
              type: string
            serialNumber:
              description: The serial number of the certificate stored in the secret named by this resource in spec.secretName.
              type: string
            conditions:
              description: conditions provides information about the certificate request.
              items:
                properties:
                  lastTransitionTime:
                    description: lastTransitionTime is the time of the last update to the current status object.
                    format: date-time
                    type: string
                  message:
                    description: message provides additional information about the current condition. This is only to be consumed by humans.
                    type: string
                  reason:
                    description: reason is the reason for the condition's last transition. Reasons are CamelCase
                    type: string
                  status:
                    description: State contains the current state of this resource.
                    enum:
                    - ""
                    - ready
                    - processing
                    - expired
                    - errored
                    type: string
                  type:
                    description: type specifies the state of the operator's reconciliation
                      functionality.
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                type: object
              type: array
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
