apiVersion: certman.managed.openshift.io/v1alpha1
kind: Certificate
metadata:
  name: example-certificate
spec:
  baseDnsDomain: tejas.openshift.com
  certSecretName: tparikh-openshift-com-tls
  awsSecretName: aws-secret
  dnsNames:
  - abc.tejas.openshift.com
  - xyz.tejas.openshift.com
  renewBefore: 15d
  